algoritmo "SomaParametrosReferencia"
var
   X, Y: Inteiro
Procedimento Soma (var A, B: Inteiro)
inicio
   A <- A + 1
   B <- B + 1
   Escreval ("O valor de A = ", A)
   Escreval ("O valor de B = ", B)
   Escreval ("A soma de A + B = ", A + B)
FimProcedimento
inicio
   X <- 4
   Y <- 8
   Soma (X, Y)
   Escreval ("o valor de X = ", X)
   Escreval ("o valor de Y = ", Y)
   Escreval ("A soma de X + Y = ", X + Y)
   
fimalgoritmo
