algoritmo "semnome"
var
   cont, N, S: Inteiro
inicio
      cont <- 1
      S <- 0
      Enquanto (cont <= 10) faca
         Escreva ("Digite o ", cont, "o. valor : ")
         Leia (N)
         Se (N > maior) entao
            maior <- N
         FimSe
         S <- S + N
         cont <- cont + 1
      FimEnquanto
      Escreval ("A soma de todos os valores foi ", S)
      Escreval ("O maior valor digitado foi ", maior)
      
         

fimalgoritmo
